format_version: 10
pipelines:
  test-pipeline-import:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-8bd31cc:
        git: https://github.com/Tanakornl3oom/gocd-101.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - test-job-import:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            job-test-import:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ./gocd/README.md
                    command: cat
                    run_if: passed
            job-test-1-import:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ./gocd/test/test.sh
                    command: bash
                    run_if: passed
